version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      database: 'db'
      user: 'user'
      password: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - witcher_networks
  main:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/main
    restart: always
    ports:
        - 8000:8000
    environment:
      - database=db
      - user=user
      - password=password
      - host=db
    networks:
      - witcher_networks
    depends_on:
      - db

volumes:
  my-db:

networks:
  witcher_networks:
