version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - wither_networks
  main:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/main
    restart: always
    ports:
        - 8000:8000
    environment:
      - database=db
      - user=root
      - password=
      - host=db
    networks:
      - wither_networks
    depends_on:
      - db

volumes:
  my-db:

networks:
  wither_networks:
